services:
  users-db:
    image: postgres:16-alpine
    container_name: fitflow-users-db

    environment:
      POSTGRES_DB: ${USERS_DB_NAME}
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - users-db-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${USERS_DB_USER} -d ${USERS_DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  users-db-data: